### ISSUE TITLE
1.0.0 Tracking Issue

### ISSUE THREAD

**Issue by gennyble** [gennyble/hext#9]
- [ ] Pay attention to the kind of negative (#6)
- [ ] Documentation on the format (#8)
- [ ] Documentation on the library
- [ ] Auto checksums and length filling would make hext inredibly more helpful (#2)
- [ ] #7
